### PR TITLE
Bring back the computer screen module

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by codemunkie15** [comment]
Just spent like an hour trying to figure out when and why this was removed! Was really looking forward to using this module after I saw it on the FTB wiki...

Anyone know when/why it was removed?

**Comment by josephcsible** [comment]
The mod was pretty much gutted when it was upgraded from 1.7.10 to 1.8, then things slowly started getting put back. This just fell through the cracks I guess.

**Comment by codemunkie15** [comment]
Ah ok. Well thanks for the re-implementation! Gonna have to figure out how to do a build with this now :P

**Comment by josephcsible** [comment]
```bash
git clone -b computermodule https://github.com/josephcsible/RFTools.git
cd RFTools
./gradlew build
```

The jar will end up at `build/libs/rftools-1.12-7.13.jar`.

**Comment by codemunkie15** [comment]
Thanks very much! Is there an easy way for me to port this to 1.10.2?

**Comment by josephcsible** [comment]
Assuming you know Java, it shouldn't be difficult at all. Just be mindful of the 1.10/1.11 situation.

**Comment by McJty** [comment]
@josephcsible can you comment on this ticket (it is for 1.10.2): https://github.com/McJty/RFTools/issues/1466
Can we solve this?

**Comment by josephcsible** [comment]
Commented there. Not convinced that it's actually our fault, pending answers to those questions.

**Pull request merged**
