### PR TITLE
Re-enable OpenComputers integration in RFTools.

### PR DESCRIPTION
**Pull request by 12foo**
OC integration was broken for two reasons:

1. There's been a small change in the OC API, which also needed a fix in
McJtyLib (see McJty/McJtyLib#41). The ManagedEnvironment class was
renamed to AbstractManagedEnvironment.

2. Forge mod loading forces lowercase mod IDs since sometime around
1.11, so "OpenComputers" is now "opencomputers".

### CODE REVIEW

**Comment by McJty** [comment]
I had to revert this because it doesn't compile for me. It cannot find AbstractManagedEnvironment

**Comment by McJty** [comment]
Hmm it may have been because you forgot to update build.gradle so the wrong version of OC was being used. Can you resubmit the PR (also to the other project) with a correct build.gradle? Thanks

**Comment by 12foo** [comment]
That's odd, I definitely compiled/tested this before doing the PR, and it should work with this build.gradle. I'll check everything once more.

**Comment by McJty** [comment]
Well it cannot work with this build.gradle as you need to fetch another version of OC so it must be updated to the newer version:

    compile "li.cil.oc:OpenComputers:MC1.10.2-1.6.+:api"

**Comment by 12foo** [comment]
Hmm. It should fetch `MC1.12.2-1.7.*` according to the build.gradle in this PR (correct OC API for 1.12). Are you maybe compiling against the 1.11 branch of McJtyLib instead of 1.12?

**Comment by McJty** [comment]
I'm talking about RFTools:

https://github.com/McJty/RFTools/blob/1.12/build.gradle#L94

**Comment by 12foo** [comment]
I can confirm that the original pull request definitely compiles and pulls in the correct version of OC. However since the original pull request was made against the previous RFTools 6 stable, I'm guessing your work on RFTools 7 changed that line back to the old OC version at some point. I'll do a new PR against the 1.12 HEAD. :)

**Comment by 12foo** [comment]
The original PRs against the other projects should be fine since those move more slowly and the PRs were made against their current HEADS, so I'll just revert your revert on McJtyLib, if that's all right?

**Pull request merged**
