### PR TITLE
OpenComputers integration in RFTools (for 1.11).

### PR DESCRIPTION
**Pull request by 12foo**
Same as the 1.12 commit, but on a different OC version.
Requires McJtyLib 1.11 with the same changes.

### CODE REVIEW

**Comment by McJty** [comment]
Will this cause problems for my 1.10/1.11 mods? Note that all my mods share the same code/jar on 1.10/1.11. i.e. it is the same mod for both MC versions. 1.12 is separate

**Comment by 12foo** [comment]
Ah, good point! That might be a problem. I'll see if there's a way around it, but in that case it might be best to just not ship OC support for 1.11.

**Comment by josephcsible** [comment]
I think this can be closed, between what's already been merged since it was created and #1489.

**Comment by McJty** [comment]
@josephcsible btw, if you have a chance it would be nice if you could check if Deep Resonance OC integration is still functional in 1.10, 1.11, and 1.12. Thanks!

**Comment by josephcsible** [comment]
It's not quite right. I'll try to get a PR in for it this week. Anyway, this PR can in fact be closed now; everything it tried to do has been done.

**Pull request closed without merging**
