### PR TITLE
RandomizeSeed config option

### PR DESCRIPTION
**Pull request by Strikingwolf**
This config option will make the dimlet seed random instead of relying on the world
seed if it is enabled.

### CODE REVIEW

**Comment by Gideonseymour** [comment]
Makes seeds completely random rather than based on world seed and dimlets

**Comment by Strikingwolf** [comment]
Exactly. It is currently on a 1000 basis. Although I could add a config option for that if need be

**Comment by Strikingwolf** [comment]
Currently not working

**Comment by Strikingwolf** [comment]
Works now

**Comment by Strikingwolf** [comment]
Also, @Gideonseymour is slightly wrong. It still uses the dimlets, thus you won't end up with blue sun if you put in red sun :laughing: Just not based on world seed

**Comment by Gideonseymour** [comment]
This is replicated in #81 . Not certain how github works in the merging of multiple commits doing the same thing.

**Pull request merged**
