### PR TITLE
Update gradle

### PR DESCRIPTION
**Pull request by shadowfacts**

### CODE REVIEW

**Comment by McJty** [comment]
Why is it needed to depend on such a recent forge version? I usually prefer to depend on older versions unless I absolutely need newer so that I know my mod is more compatible with older versions too.

Additionally you upgraded gradlew.bat but not the linux script. I'm a bit scared to merge this as I need the 'gradlew' script and don't understand exactly what you're changing here.

**Comment by shadowfacts** [comment]
Whoops, I needed to update Forge because I was testing with a mod in my dev env that required a newer version.

The Gradle Wrapper is just a set of scripts and a jar file automatically download and use the specified version of Gradle, saving the user the hassle of installing it themselves. In a version of Gradle between 2.0 (what you had been using) and 2.6 (the latest) changes (bugfixes and/or improvements) were made to the Windows wrapper script while the Linux/Mac one stayed the same. Gradle 2.6 works perfectly fine (better, in some cases) and upgrading will not affect anything.

**Comment by McJty** [comment]
Ok. I will try and test this out later before I confirm the merge.

**Comment by shadowfacts** [comment]
I can guarantee it does, I'm using Gradle 2.6 for all of my projects.

**Pull request merged**
